### ISSUE TITLE
error yarn run import 

### ISSUE THREAD

**Issue by pribadihcr** [malgamves/next-multimodal-search-demo#2]
Hi when running
```
$ yarn run import 
```

I got the following error:
```
next-multimodal-search-demo/node_modules/rimraf/dist/esm/bin.mjs:2
import { readFile } from 'fs/promises';
^^^^^^

SyntaxError: Unexpected token import
    at createScript (vm.js:80:10)
    at Object.runInThisContext (vm.js:139:10)
    at Module._compile (module.js:616:28)
    at Object.Module._extensions..js (module.js:663:10)
    at Module.load (module.js:565:32)
    at tryModuleLoad (module.js:505:12)
    at Function.Module._load (module.js:497:3)
    at Function.Module.runMain (module.js:693:10)
    at startup (bootstrap_node.js:188:16)
    at bootstrap_node.js:609:3
error Command failed with exit code 1.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.

```

Any solution?. Thank you very much

**Comment by malgamves** [comment]
thanks for coming here, this should be fixed in the [new client update](https://github.com/weaviate-tutorials/next-multimodal-search-demo/pull/4/)
